kurento:
- ip: 192.168.1.124
  url: ws://192.168.1.124:8888/kurento
video-transposing-ceiling: 50
audio-transposing-ceiling: 100
localIpAddress: 192.168.1.124
acceptSelfSignedCertificate: false
redisHost: 127.0.0.1
redisPort: "6379"
clientPort: "3008"
minVideoPort: 30000
maxVideoPort: 33000
mediaFlowTimeoutDuration: 15000
from-screenshare: from-screenshare-sfu
to-screenshare: to-screenshare-sfu
from-video: from-video-sfu
to-video: to-video-sfu
from-audio: from-audio-sfu
to-audio: to-audio-sfu
to-akka: to-akka-apps-redis-channel
from-akka: from-akka-apps-redis-channel
to-stream: to-sfu-redis-channel
from-stream: from-stream-sfu
to-html5: to-html5-redis-channel
common-message-version: 2.x
screenshareKeyframeInterval: 2
recordScreenSharing: true
recordWebcams: true
recordingBasePath: file:///var/kurento
recordingMediaProfile: MKV_VIDEO_ONLY
recordingFormat: mkv
redisExpireTime: 1209600
mcs-path: /mcs
mcs-port: 3010
mcs-address: localhost
mcs-ws-timeout: 30000
freeswitch:
  ip: 192.168.1.124
  port: "5066"
  esl_ip: ESL_IP
  esl_port: ESL_PORT
log:
  filename: /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log
  level: verbose
bbb-stream:
  image_name: bbb-stream
  container_type: docker
  bigbluebutton_url: BBBHOST
  bigbluebutton_secret: BBBSECRET
  bot_join_options:
    userdata-html5autoswaplayout: false
    userdata-html5hidepresentation: false
  k8s:
    namespace: default
    template:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: bbb-stream-
      spec:
        template:
          spec:
            containers:
            - name: bbb-stream-firefox
              image: gcr.io/PROJECT-ID/bbb-stream
              env:
              - name: LINK
                value: ""
              - name: OUTPUT
                value: ""
            restartPolicy: OnFailure
        backoffLimit: 0
processes:
- path: ./lib/mcs-core/process.js
- path: ./lib/screenshare/ScreenshareProcess
- path: ./lib/video/VideoProcess.js
- path: ./lib/audio-kurento/AudioProcess.js
#- path: ./lib/audio/AudioProcess.js
media-server-adapters:
- path: kurento/kurento.js
  name: Kurento
- path: freeswitch/freeswitch.js
  name: Freeswitch
conference-media-specs:
  codec_video_main: VP8
  codec_video_content: VP8
  codec_audio: ANY
  H264:
    profile_level_id: 42e01f
    packetization_mode: "0"
    level_asymmetry_allowed: "0"
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
    max_mbps_main: "0"
    max_fs_main: "0"
    max_br_main: "0"
    max_mbps_content: "0"
    max_fs_content: "12288"
    max_br_content: "0"
  VP8:
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
  OPUS:
    useinbandfec: "0"
    maxaveragebitrate: "30000"
    maxplaybackrate: "48000"
    ptime: "20"
    minptime: "10"
    maxptime: "40"
